name: Build

on: [push]

defaults:
  run:
    shell: bash
    working-directory: wow-recorder

jobs:
  Build:
    name: Build release binaries

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip pyinstaller pytest
          pip install -r requirements.txt

      - name: Build with pyinstaller
        run: pyinstaller --onefile --console --name=wow-recorder-${{ matrix.os }} main.py

      - name: copy script file
        run: cp run.sh dist/run.sh

      - name: Deploy artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wow-recorder-${{ matrix.os }}
          path: | 
            wow-recorder/dist/wow-recorder-${{ matrix.os }}*
            wow-recorder/dist/run.sh
          if-no-files-found: error
